name: ci-phase1

on:
  push:
    branches:
      - master
      - main

jobs:

  # ======================
  # CI TEST JOB
  # ======================
  CI:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python app/app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputfile
          path: output.txt

  # ======================
  # BUILD & PUSH JOB
  # ======================
  build:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag 
        run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/myapp:${{ env.TAG }} .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/myapp:${{ env.TAG }}   