name: ci-phase1

on:
  push:
    branches:
      - main

jobs:

# ======================
# CI TEST JOB
# ======================
  CI:

    runs-on: ubuntu-latest

    container:
      image: python:3.12

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install_dependencies
        run: pip install -r requirements.txt

      - name: run_app
        run: python app/app.py

      - name: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputfile
          path: output.txt


# ======================
# BUILD IMAGE JOB
# ======================
  build:

    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker_login
        run: echo "${{ secrets.DOCKER_PASS }}" |
             docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: docker_build
        run: docker build -t ${{ secrets.DOCKER_USER }}/myapp:latest .

      - name: docker_push
        run: docker push ${{ secrets.DOCKER_USER }}/myapp:latest